### ISSUE TITLE
Swaped Lat and Lng values

### ISSUE THREAD

**Issue by yegorLitvinov** [erdem/django-map-widgets#60]
This can be an error:
[Here](https://github.com/erdem/django-map-widgets/blob/c92f912043450a18d127a3b64306a9b1af63564c/mapwidgets/widgets.py#L23) x1 is described as a latitude
But [here](https://github.com/erdem/django-map-widgets/blob/c92f912043450a18d127a3b64306a9b1af63564c/mapwidgets/widgets.py#L113) it is assigned to variable as a longitude

And I have noticed, that there is no description of lat and lng mapping to postgis `Point.x` and `Point.y` in documentation ( i guess [lng, lat] ).

**Comment by erdem** [comment]
I noticed this issue but I didn't released the fix yet because of some compatibility issues. 

https://github.com/erdem/django-map-widgets/tree/v0.2.0 

This is the branch which I am developing the new release, you can install the package from here, it might be work for you.

**Comment by yegorLitvinov** [comment]
Ok, thanks!

**Comment by felocru** [comment]
Hello, I am presenting the same problem. The values of lat and lng are stored in my BD upside down. This detail has not been solved?
I have:
`"coordinates": [
                        -89.61225539999998,
                        20.9593969
                    ],
                    "type": "Point"`
Must be:
`"coordinates": [
                        20.9593969,
                       -89.61225539999998
                    ],
                    "type": "Point"`

**Comment by erdem** [comment]
@felocru I fixed this issue in the latest version. Where are you getting this response?

**Comment by felocru** [comment]
Hello @erdem I have version 0.2.0. I realized that in the database they are stored upside down. When I reload the page with the maps, it takes me to Antarctica. In the file django_mw_base.js I am seeing:
![image](https://user-images.githubusercontent.com/11906313/46749018-84bf3500-cc7a-11e8-9042-8ea23d9f9a67.png)
I understand that it is inverted.
I installed with pip install.

**Comment by erdem** [comment]
Hi @felocru

I reproduced this one. You are right; the values are swapping here. The parameters are correct, but the formatted string is wrong. I will release a hot-fix version for this issue ASAP. 

Thanks

**Comment by erdem** [comment]
`pip install git+git://github.com/erdem/django-map-widgets.git@v0.2.1`

@felocru Could you test the package from this hot-fix branch?  it's looking fine to me.

**Comment by erdem** [comment]
`pip install git+git://github.com/erdem/django-map-widgets.git@v0.2.1`

@felocru I fix the bug in a hotfix branch, it's looking fine to me. I will publish the fix soon if I didn't get any bad feedback from you.

**Comment by erdem** [comment]
https://github.com/erdem/django-map-widgets/releases/tag/v0.2.1

**Comment by helio-correia** [comment]
Hi, I'm having this problem with the 0.2.1. On the admin, when I add a location it adds nicely. The problem is when visit the edit view the coordinates is already swapped.

**Comment by tuky** [comment]
I have a feeling that this "hotfix" was overpaced and is causing problems now, too. when storing coordinates as points, the default is x = longitude, y = latitude. It's everywhere in the code, too:

https://github.com/erdem/django-map-widgets/blob/master/mapwidgets/widgets.py#L311
https://github.com/erdem/django-map-widgets/blob/master/mapwidgets/widgets.py#L98

and i think, that's the commonly preferred way all around: https://www.benjaminspaulding.com/2015/09/01/long-x-lat-free-illustration-included/ https://gis.stackexchange.com/a/68856 (x: left-right; y: top-down).

brief example New York: Latitude and longitude coordinates are roughly: 40.7, -73.9. with this new release `0.2.1` we now have

```python
>>> from mapwidgets.widgets import *
>>> w = BasePointFieldMapWidget()
>>> p = w.deserialize("POINT (40.7 -73.9)")
>>> p.x
40.7
>>> p.y
-73.9
>>> p.coords
(40.7, -73.9)
```

so `x` is now the latitude, but all other code expects it to be the longitude.

**Comment by stphnthiel** [comment]
This issue should be reopened. I was temporarily able to work around the issue by overwriting the model’s save method.

```python
def save(self, *args, **kwargs):
    x = self.coordinates.x
    self.coordinates.x = self.coordinates.y
    self.coordinates.y = x
    super(Location, self).save(*args, **kwargs)
```

Is it best to open a PR?

**Comment by erdem** [comment]
Hi guys, 

I didn't follow the issues for a while, I was on a long trip. 

I'll check this issue again.

**Comment by IRIDON** [comment]
Hi, after this hotfix i have this problem.
https://www.awesomescreenshot.com/image/3831147/d4f8441bb315b23d79230d016d0d1ac8
after cave, i get this
https://www.awesomescreenshot.com/image/3831151/67cd3056ebf7ca0e930283a7e7c45411

**Comment by pasevin** [comment]
@erdem any idea when you will be able to look into this?

**Comment by erdem** [comment]
@pasevin I am planning to look into it this week. I'll update the topic when I pushed the patch.

**Comment by erdem** [comment]
@tuky Thank you for the investigation, you are right the patch was buggy. The thing is there was another case making the coordinates reverse before the patch. I reproduced. I'll add some extra test cases for this project when I catch a time. 

However, I reverted the patch in a different branch. As far as I tested, I didn't see the swapped values problem. 

`pip install git+git://github.com/erdem/django-map-widgets.git@v0.2.1`

@pasevin Would be good if you can install the package from the new branch and update the topic after seeing the results.

**Comment by pasevin** [comment]
I can confirm has no issue with coords.
pip install git+https://github.com/erdem/django-map-widgets.git@v0.2.2

**Comment by dennishylau** [comment]
@pasevin Watch out, I believe v0.2.2 is still not right. If I disable the widget and print the field, it gives `SRID=4326;POINT (long lat)`, while enabling it gives `SRID=4326;POINT (lat long)`

**Comment by pasevin** [comment]
@dennishylau could be the case, I'm using the widget only and it works for me on the admin page.

**Comment by erdem** [comment]
@dennishylau Where have you printed the field value exactly? Is it a model `save` method? 

Could you share your whole test case flow?

**Comment by dennishylau** [comment]
@erdem Thank you for this widget. 
That's correct, I printed it in `save()` before calling super's `save()`.
I simply commented out `models.PointField: {"widget": GooglePointFieldWidget}` and printed, don't have a full test case for it yet.

**Comment by raelmax** [comment]
> This issue should be reopened. I was temporarily able to work around the issue by overwriting the model’s save method.
> 
> ```python
> def save(self, *args, **kwargs):
>     x = self.coordinates.x
>     self.coordinates.x = self.coordinates.y
>     self.coordinates.y = x
>     super(Location, self).save(*args, **kwargs)
> ```
> 
> Is it best to open a PR?

I used this snippet to work around this bug, but it only works if you set `MINIFIED` to False on your settings. I think that may have any difference between minified and original versions.

**Comment by gidantribal** [comment]
Guys, so which version should be taken to verify the coords aren't swapped? The latest official release is still swapping coords at model save.

**Comment by gidantribal** [comment]
And, most important, why the fix in my PR doesn't work? (pull request #95). If not, it's a good point to start anyway, because the JS script is clearly wrong. Hope to help!

**Comment by erdem** [comment]
@gidantribal Thanks for the contribution but I already add the same fix with yours to `v.0.2.2` version. Check out my comments on top.

**Comment by erdem** [comment]
I pushed to `0.2.2` version to PyPI. I didn't see any swapped coordinates issue in this version as far as I tested on my project. 

`pip install django-map-widgets==0.2.2`

Thank you all!

**Comment by gidantribal** [comment]
Thanks erdem for your work. I'll double check ASAP if 0.2.2 fixes out of the box!

**Comment by dennishylau** [comment]
Sorry I was mistaken, can confirm 0.2.2 actually fixes the problem. Thanks for the great work.

If you still see the problem, remember to run `manage.py collectstatic` again and clear browser cache of the js files!

**Comment by vicobits** [comment]
I used a tempral fix
```
class FixedGooglePointFieldWidget(GooglePointFieldWidget):

    def render(self, name, value, attrs=None, renderer=None):
        if isinstance(value,  Point):
            x = value.x
            value.x = value.y
            value.y = x
        return super(FixedGooglePointFieldWidget, self).render(name, value, attrs, renderer)
```

**Comment by erdem** [comment]
@vicobits You don't need to use temporary fix anymore. I upgraded the package. Check my previous comment on top.
